version: '3'
services:
  haaukins-exercises:
    container_name: haaukins-exercises
    env_file:
      - .env
    build: .
    ports:
      - 50095:50095       #change them according the .env file
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - ${CONFIG_PATH}:/config.yml:ro  # mount config file
    networks:
      - internal

  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    networks:
      - internal

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    networks:
      - internal

networks:
  internal:
    driver: bridge