version: '3'
services:
  haaukins-exercises:
    container_name: haaukins-exercises
    env_file:
      - .env
    image: aaunetworksecurity/haaukins-exercises:latest
    ports:
      - 50095:50095
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - ${CONFIG_PATH}:/config.yml:ro
    networks:
      - internal

  mongo:
    image: mongo:5
    env_file:
      - .env
    restart: always
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    networks:
      - internal

networks:
  internal:
    driver: bridge