// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exercise.proto

package exercise

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ChildExercise struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EnvFlag              string   `protobuf:"bytes,3,opt,name=env_flag,json=envFlag,proto3" json:"env_flag,omitempty"`
	Points               int32    `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	TeamDescription      string   `protobuf:"bytes,6,opt,name=team_description,json=teamDescription,proto3" json:"team_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChildExercise) Reset()         { *m = ChildExercise{} }
func (m *ChildExercise) String() string { return proto.CompactTextString(m) }
func (*ChildExercise) ProtoMessage()    {}
func (*ChildExercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{1}
}

func (m *ChildExercise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildExercise.Unmarshal(m, b)
}
func (m *ChildExercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildExercise.Marshal(b, m, deterministic)
}
func (m *ChildExercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildExercise.Merge(m, src)
}
func (m *ChildExercise) XXX_Size() int {
	return xxx_messageInfo_ChildExercise.Size(m)
}
func (m *ChildExercise) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildExercise.DiscardUnknown(m)
}

var xxx_messageInfo_ChildExercise proto.InternalMessageInfo

func (m *ChildExercise) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ChildExercise) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChildExercise) GetEnvFlag() string {
	if m != nil {
		return m.EnvFlag
	}
	return ""
}

func (m *ChildExercise) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *ChildExercise) GetTeamDescription() string {
	if m != nil {
		return m.TeamDescription
	}
	return ""
}

type Exercise struct {
	Tag                  string           `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             string           `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Children             []*ChildExercise `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Exercise) Reset()         { *m = Exercise{} }
func (m *Exercise) String() string { return proto.CompactTextString(m) }
func (*Exercise) ProtoMessage()    {}
func (*Exercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{2}
}

func (m *Exercise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exercise.Unmarshal(m, b)
}
func (m *Exercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exercise.Marshal(b, m, deterministic)
}
func (m *Exercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exercise.Merge(m, src)
}
func (m *Exercise) XXX_Size() int {
	return xxx_messageInfo_Exercise.Size(m)
}
func (m *Exercise) XXX_DiscardUnknown() {
	xxx_messageInfo_Exercise.DiscardUnknown(m)
}

var xxx_messageInfo_Exercise proto.InternalMessageInfo

func (m *Exercise) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Exercise) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Exercise) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Exercise) GetChildren() []*ChildExercise {
	if m != nil {
		return m.Children
	}
	return nil
}

type GetExercisesResponse struct {
	Exercises            []*Exercise `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetExercisesResponse) Reset()         { *m = GetExercisesResponse{} }
func (m *GetExercisesResponse) String() string { return proto.CompactTextString(m) }
func (*GetExercisesResponse) ProtoMessage()    {}
func (*GetExercisesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{3}
}

func (m *GetExercisesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExercisesResponse.Unmarshal(m, b)
}
func (m *GetExercisesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExercisesResponse.Marshal(b, m, deterministic)
}
func (m *GetExercisesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExercisesResponse.Merge(m, src)
}
func (m *GetExercisesResponse) XXX_Size() int {
	return xxx_messageInfo_GetExercisesResponse.Size(m)
}
func (m *GetExercisesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExercisesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetExercisesResponse proto.InternalMessageInfo

func (m *GetExercisesResponse) GetExercises() []*Exercise {
	if m != nil {
		return m.Exercises
	}
	return nil
}

type GetExerciseByTagsRequest struct {
	Tag                  []string `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExerciseByTagsRequest) Reset()         { *m = GetExerciseByTagsRequest{} }
func (m *GetExerciseByTagsRequest) String() string { return proto.CompactTextString(m) }
func (*GetExerciseByTagsRequest) ProtoMessage()    {}
func (*GetExerciseByTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{4}
}

func (m *GetExerciseByTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExerciseByTagsRequest.Unmarshal(m, b)
}
func (m *GetExerciseByTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExerciseByTagsRequest.Marshal(b, m, deterministic)
}
func (m *GetExerciseByTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExerciseByTagsRequest.Merge(m, src)
}
func (m *GetExerciseByTagsRequest) XXX_Size() int {
	return xxx_messageInfo_GetExerciseByTagsRequest.Size(m)
}
func (m *GetExerciseByTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExerciseByTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExerciseByTagsRequest proto.InternalMessageInfo

func (m *GetExerciseByTagsRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GetExerciseByCategoryRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExerciseByCategoryRequest) Reset()         { *m = GetExerciseByCategoryRequest{} }
func (m *GetExerciseByCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetExerciseByCategoryRequest) ProtoMessage()    {}
func (*GetExerciseByCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{5}
}

func (m *GetExerciseByCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExerciseByCategoryRequest.Unmarshal(m, b)
}
func (m *GetExerciseByCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExerciseByCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetExerciseByCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExerciseByCategoryRequest.Merge(m, src)
}
func (m *GetExerciseByCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetExerciseByCategoryRequest.Size(m)
}
func (m *GetExerciseByCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExerciseByCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExerciseByCategoryRequest proto.InternalMessageInfo

func (m *GetExerciseByCategoryRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type AddExerciseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddExerciseRequest) Reset()         { *m = AddExerciseRequest{} }
func (m *AddExerciseRequest) String() string { return proto.CompactTextString(m) }
func (*AddExerciseRequest) ProtoMessage()    {}
func (*AddExerciseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{6}
}

func (m *AddExerciseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddExerciseRequest.Unmarshal(m, b)
}
func (m *AddExerciseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddExerciseRequest.Marshal(b, m, deterministic)
}
func (m *AddExerciseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddExerciseRequest.Merge(m, src)
}
func (m *AddExerciseRequest) XXX_Size() int {
	return xxx_messageInfo_AddExerciseRequest.Size(m)
}
func (m *AddExerciseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddExerciseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddExerciseRequest proto.InternalMessageInfo

type ResponseStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{7}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

type UpdateExerciseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateExerciseRequest) Reset()         { *m = UpdateExerciseRequest{} }
func (m *UpdateExerciseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateExerciseRequest) ProtoMessage()    {}
func (*UpdateExerciseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_072c1ef9e72c0732, []int{8}
}

func (m *UpdateExerciseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateExerciseRequest.Unmarshal(m, b)
}
func (m *UpdateExerciseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateExerciseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateExerciseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateExerciseRequest.Merge(m, src)
}
func (m *UpdateExerciseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateExerciseRequest.Size(m)
}
func (m *UpdateExerciseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateExerciseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateExerciseRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*ChildExercise)(nil), "ChildExercise")
	proto.RegisterType((*Exercise)(nil), "Exercise")
	proto.RegisterType((*GetExercisesResponse)(nil), "GetExercisesResponse")
	proto.RegisterType((*GetExerciseByTagsRequest)(nil), "GetExerciseByTagsRequest")
	proto.RegisterType((*GetExerciseByCategoryRequest)(nil), "GetExerciseByCategoryRequest")
	proto.RegisterType((*AddExerciseRequest)(nil), "AddExerciseRequest")
	proto.RegisterType((*ResponseStatus)(nil), "ResponseStatus")
	proto.RegisterType((*UpdateExerciseRequest)(nil), "UpdateExerciseRequest")
}

func init() { proto.RegisterFile("exercise.proto", fileDescriptor_072c1ef9e72c0732) }

var fileDescriptor_072c1ef9e72c0732 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0xda, 0x71, 0x36, 0x53, 0x9a, 0x9a, 0xa1, 0x29, 0xdb, 0x08, 0xa4, 0x68, 0x2f,
	0x04, 0x84, 0x16, 0xa9, 0x88, 0x0b, 0x1c, 0x10, 0x94, 0x52, 0x29, 0x17, 0x24, 0x17, 0xce, 0xd5,
	0x12, 0x0f, 0xc6, 0x52, 0x62, 0x1b, 0xef, 0xb6, 0x22, 0x17, 0x5e, 0x85, 0x37, 0xe2, 0x99, 0x50,
	0x16, 0x3b, 0xb6, 0x5b, 0x07, 0xa9, 0xb7, 0x9d, 0x7f, 0x66, 0x7e, 0xcd, 0xff, 0xc9, 0x86, 0x21,
	0xfd, 0xa4, 0x62, 0x9e, 0x68, 0x92, 0x79, 0x91, 0x99, 0x4c, 0xf4, 0xa1, 0x77, 0xb6, 0xcc, 0xcd,
	0x4a, 0xfc, 0x76, 0x60, 0xff, 0xf4, 0x7b, 0xb2, 0x88, 0xce, 0xca, 0x01, 0x0c, 0xc0, 0x35, 0x2a,
	0xe6, 0xce, 0xc4, 0x99, 0x0e, 0xc2, 0xf5, 0x13, 0x11, 0xbc, 0x54, 0x2d, 0x89, 0xef, 0x5a, 0xc9,
	0xbe, 0xf1, 0x18, 0x18, 0xa5, 0xd7, 0x97, 0xdf, 0x16, 0x2a, 0xe6, 0xae, 0xd5, 0xfb, 0x94, 0x5e,
	0x7f, 0x5c, 0xa8, 0x18, 0x8f, 0xc0, 0xcf, 0xb3, 0x24, 0x35, 0x9a, 0x7b, 0x13, 0x67, 0xda, 0x0b,
	0xcb, 0x0a, 0x9f, 0x42, 0x60, 0x48, 0x2d, 0x2f, 0x23, 0xd2, 0xf3, 0x22, 0xc9, 0x4d, 0x92, 0xa5,
	0xdc, 0xb7, 0xab, 0x07, 0x6b, 0xfd, 0x43, 0x2d, 0xcf, 0x3c, 0xd6, 0x0b, 0xfc, 0x99, 0xc7, 0xfa,
	0x01, 0x13, 0xbf, 0x80, 0xdd, 0xf1, 0xb6, 0x31, 0xb0, 0xb9, 0x32, 0x14, 0x67, 0xc5, 0xca, 0x9e,
	0x30, 0x08, 0x37, 0x35, 0x3e, 0x03, 0x36, 0x5f, 0xc7, 0x2d, 0x28, 0xe5, 0xbd, 0x89, 0x3b, 0xdd,
	0x3b, 0x19, 0xca, 0x56, 0xfe, 0x70, 0xd3, 0x9f, 0x79, 0xcc, 0x0d, 0x3c, 0xf1, 0x16, 0x0e, 0xcf,
	0xc9, 0x54, 0x6d, 0x1d, 0x92, 0xce, 0xb3, 0x54, 0x13, 0x3e, 0x81, 0x41, 0x05, 0x55, 0x73, 0xc7,
	0x5a, 0x0d, 0xe4, 0xc6, 0xa5, 0xee, 0x89, 0xe7, 0xc0, 0x1b, 0x06, 0xef, 0x57, 0x9f, 0x55, 0xac,
	0x43, 0xfa, 0x71, 0x45, 0xda, 0xd4, 0x81, 0xdc, 0x32, 0x90, 0x78, 0x0d, 0x8f, 0x5a, 0xd3, 0xa7,
	0xe5, 0xe5, 0xd5, 0x46, 0x33, 0x9c, 0xd3, 0x0e, 0x27, 0x0e, 0x01, 0xdf, 0x45, 0x75, 0x92, 0x7f,
	0x1b, 0x22, 0x80, 0x61, 0x75, 0xf4, 0x85, 0x51, 0xe6, 0x4a, 0x8b, 0x87, 0x30, 0xfa, 0x92, 0x47,
	0xca, 0xd0, 0x8d, 0xd1, 0x93, 0x3f, 0xbb, 0xb0, 0x5f, 0x69, 0x17, 0x26, 0x2b, 0x08, 0x5f, 0xc0,
	0xbd, 0x66, 0x7a, 0xf4, 0xa5, 0xfd, 0x6e, 0xc6, 0x23, 0xd9, 0x05, 0x45, 0xec, 0xe0, 0x39, 0xdc,
	0xbf, 0x95, 0x16, 0x8f, 0xe5, 0x36, 0x02, 0xdb, 0x8d, 0x3e, 0xc1, 0xa8, 0x13, 0x04, 0x3e, 0x96,
	0xff, 0x03, 0xb4, 0xdd, 0xf0, 0x15, 0xec, 0x35, 0xe8, 0xe0, 0x03, 0x79, 0x9b, 0xd5, 0xf8, 0x40,
	0xde, 0x40, 0xb5, 0x83, 0x6f, 0x60, 0xd8, 0x86, 0x85, 0x47, 0xb2, 0x93, 0x5e, 0xc7, 0xf2, 0x57,
	0xdf, 0xfe, 0x6e, 0x2f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xd4, 0xb2, 0x6c, 0x80, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExerciseStoreClient is the client API for ExerciseStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExerciseStoreClient interface {
	GetExercises(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetExercisesResponse, error)
	GetExerciseByTags(ctx context.Context, in *GetExerciseByTagsRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error)
	GetExerciseByCategory(ctx context.Context, in *GetExerciseByCategoryRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error)
	//todo future implementation, those will be managed by the webclient
	AddExercise(ctx context.Context, in *AddExerciseRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	UpdateExercise(ctx context.Context, in *UpdateExerciseRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type exerciseStoreClient struct {
	cc *grpc.ClientConn
}

func NewExerciseStoreClient(cc *grpc.ClientConn) ExerciseStoreClient {
	return &exerciseStoreClient{cc}
}

func (c *exerciseStoreClient) GetExercises(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetExercisesResponse, error) {
	out := new(GetExercisesResponse)
	err := c.cc.Invoke(ctx, "/ExerciseStore/GetExercises", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseStoreClient) GetExerciseByTags(ctx context.Context, in *GetExerciseByTagsRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error) {
	out := new(GetExercisesResponse)
	err := c.cc.Invoke(ctx, "/ExerciseStore/GetExerciseByTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseStoreClient) GetExerciseByCategory(ctx context.Context, in *GetExerciseByCategoryRequest, opts ...grpc.CallOption) (*GetExercisesResponse, error) {
	out := new(GetExercisesResponse)
	err := c.cc.Invoke(ctx, "/ExerciseStore/GetExerciseByCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseStoreClient) AddExercise(ctx context.Context, in *AddExerciseRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/ExerciseStore/AddExercise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseStoreClient) UpdateExercise(ctx context.Context, in *UpdateExerciseRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/ExerciseStore/UpdateExercise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseStoreServer is the server API for ExerciseStore service.
type ExerciseStoreServer interface {
	GetExercises(context.Context, *Empty) (*GetExercisesResponse, error)
	GetExerciseByTags(context.Context, *GetExerciseByTagsRequest) (*GetExercisesResponse, error)
	GetExerciseByCategory(context.Context, *GetExerciseByCategoryRequest) (*GetExercisesResponse, error)
	//todo future implementation, those will be managed by the webclient
	AddExercise(context.Context, *AddExerciseRequest) (*ResponseStatus, error)
	UpdateExercise(context.Context, *UpdateExerciseRequest) (*ResponseStatus, error)
}

// UnimplementedExerciseStoreServer can be embedded to have forward compatible implementations.
type UnimplementedExerciseStoreServer struct {
}

func (*UnimplementedExerciseStoreServer) GetExercises(ctx context.Context, req *Empty) (*GetExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExercises not implemented")
}
func (*UnimplementedExerciseStoreServer) GetExerciseByTags(ctx context.Context, req *GetExerciseByTagsRequest) (*GetExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseByTags not implemented")
}
func (*UnimplementedExerciseStoreServer) GetExerciseByCategory(ctx context.Context, req *GetExerciseByCategoryRequest) (*GetExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseByCategory not implemented")
}
func (*UnimplementedExerciseStoreServer) AddExercise(ctx context.Context, req *AddExerciseRequest) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExercise not implemented")
}
func (*UnimplementedExerciseStoreServer) UpdateExercise(ctx context.Context, req *UpdateExerciseRequest) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExercise not implemented")
}

func RegisterExerciseStoreServer(s *grpc.Server, srv ExerciseStoreServer) {
	s.RegisterService(&_ExerciseStore_serviceDesc, srv)
}

func _ExerciseStore_GetExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseStoreServer).GetExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExerciseStore/GetExercises",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseStoreServer).GetExercises(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseStore_GetExerciseByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseByTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseStoreServer).GetExerciseByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExerciseStore/GetExerciseByTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseStoreServer).GetExerciseByTags(ctx, req.(*GetExerciseByTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseStore_GetExerciseByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseStoreServer).GetExerciseByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExerciseStore/GetExerciseByCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseStoreServer).GetExerciseByCategory(ctx, req.(*GetExerciseByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseStore_AddExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseStoreServer).AddExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExerciseStore/AddExercise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseStoreServer).AddExercise(ctx, req.(*AddExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseStore_UpdateExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseStoreServer).UpdateExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExerciseStore/UpdateExercise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseStoreServer).UpdateExercise(ctx, req.(*UpdateExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExerciseStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExerciseStore",
	HandlerType: (*ExerciseStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExercises",
			Handler:    _ExerciseStore_GetExercises_Handler,
		},
		{
			MethodName: "GetExerciseByTags",
			Handler:    _ExerciseStore_GetExerciseByTags_Handler,
		},
		{
			MethodName: "GetExerciseByCategory",
			Handler:    _ExerciseStore_GetExerciseByCategory_Handler,
		},
		{
			MethodName: "AddExercise",
			Handler:    _ExerciseStore_AddExercise_Handler,
		},
		{
			MethodName: "UpdateExercise",
			Handler:    _ExerciseStore_UpdateExercise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exercise.proto",
}
